name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install git ruby rpm -y
      - name: Install fpm
        run: sudo gem install fpm
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make release directory
        run: mkdir dist
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set RELEASE_NUMBER
        run: echo "RELEASE_NUMBER=${RELEASE_VERSION#v}" >> $GITHUB_ENV
      - name: Build darwin binary
        run: make build GOOS=darwin  OUTPUT=dist/git-sops_${{ env.RELEASE_VERSION }}_osx-amd64
      - name: Build windows binary
        run: make build GOOS=windows OUTPUT=dist/git-sops_${{ env.RELEASE_VERSION }}.exe
      - name: Build linux binary
        run: make build GOARCH=amd64 OUTPUT=dist/git-sops_${{ env.RELEASE_VERSION }}_linux-amd64
      - name: Build linux/arm64 binary
        run: make build GOARCH=arm64 OUTPUT=dist/git-sops_${{ env.RELEASE_VERSION }}_linux-arm64
      - name: Build deb and rpm
        run: make deb-pkg rpm-pkg
      - name: Move deb and rpm into release directory
        run: mv *.deb *.rpm dist/ && ls -1 dist/
      - name: Create release
        uses: "mozilla/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/git-sops_${{ env.RELEASE_VERSION }}.exe
            dist/git-sops_${{ env.RELEASE_VERSION }}_osx-amd64
            dist/git-sops_${{ env.RELEASE_VERSION }}_linux-amd64
            dist/git-sops_${{ env.RELEASE_VERSION }}_linux-arm64
            dist/git-sops_${{ env.RELEASE_NUMBER }}_amd64.deb
            dist/git-sops-${{ env.RELEASE_NUMBER }}-1.x86_64.rpm
